spring:
  application:
    name: eurekaclient

server:
  port: 9001

# eureka 注册中心配置
eureka:
  instance:
    hostname: localhost
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    leaseRenewalIntervalInSeconds: 5
    # 发呆时间，即服务续约到期时间（缺省为90s）
    leaseExpirationDurationInSeconds: 10
  client:
    # 拉取服务器注册信息间隔时间（缺省为30s）
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true

