spring:
  application:
    name: feign

server:
  port: 9011

# eureka 注册中心配置
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# 开启feign熔断机制，默认false，只有在服务不可用时开启熔断机制
feign:
  hystrix:
    enabled: true

# 熔断超时时间，设置为5s
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
