spring:
  application:
    name: feigncustomer

server:
  port: 9011

# eureka 注册中心配置
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
feign:
  httpclient:
    enabled: true
